version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-1
    ARTIFACT_BUCKET: aveda-resource

phases:
  install:
    runtime-versions:
      java: corretto21
      python: 3.11
    commands:
      - pip install --upgrade aws-sam-cli
  pre_build:
    commands:
      - sam validate
      - sam build --use-container
  build:
    commands:
      - sam package \
        --s3-bucket $ARTIFACT_BUCKET \
        --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-packaged-template.yaml
