AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  lambdatest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aveda-resource/uz-coupon-manage-api-1.0.0-SNAPSHOT.jar
      Description: ''
      MemorySize: 512
      Timeout: 15
      Handler: com.renwei.uz.LambdaHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: SecretsManagerDbCredentialsAccess
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:PutResourcePolicy
                - secretsmanager:PutSecretValue
                - secretsmanager:DeleteSecret
                - secretsmanager:DescribeSecret
                - secretsmanager:TagResource
              Resource: arn:aws:secretsmanager:*:*:secret:rds-db-credentials/*
            - Sid: RDSDataServiceAccess
              Effect: Allow
              Action:
                - dbqms:CreateFavoriteQuery
                - dbqms:DescribeFavoriteQueries
                - dbqms:UpdateFavoriteQuery
                - dbqms:DeleteFavoriteQueries
                - dbqms:GetQueryString
                - dbqms:CreateQueryHistory
                - dbqms:DescribeQueryHistory
                - dbqms:UpdateQueryHistory
                - dbqms:DeleteQueryHistory
                - rds-data:ExecuteSql
                - rds-data:ExecuteStatement
                - rds-data:BatchExecuteStatement
                - rds-data:BeginTransaction
                - rds-data:CommitTransaction
                - rds-data:RollbackTransaction
                - secretsmanager:CreateSecret
                - secretsmanager:ListSecrets
                - secretsmanager:GetRandomPassword
                - tag:GetResources
              Resource: '*'
            - Sid: AWSLambdaVPCAccessExecutionPermissions
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DescribeSubnets
                - ec2:DeleteNetworkInterface
                - ec2:AssignPrivateIpAddresses
                - ec2:UnassignPrivateIpAddresses
              Resource: '*'
            - Effect: Allow
              Action:
                - autoscaling:Describe*
                - cloudwatch:*
                - logs:*
                - sns:*
                - iam:GetPolicy
                - iam:GetPolicyVersion
                - iam:GetRole
                - oam:ListSinks
              Resource: '*'
            - Effect: Allow
              Action:
                - iam:CreateServiceLinkedRole
              Resource: arn:aws:iam::*:role/aws-service-role/events.amazonaws.com/AWSServiceRoleForCloudWatchEvents*
              Condition:
                StringLike:
                  iam:AWSServiceName: events.amazonaws.com
            - Effect: Allow
              Action:
                - oam:ListAttachedLinks
              Resource: arn:aws:oam:*:*:sink/*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: PublishedVersions
      VpcConfig:
        SecurityGroupIds:
          - sg-0289b9a39d9f06ccc
        SubnetIds:
          - subnet-058251f891bfd9d0e
          - subnet-07adaf1afc08f0f79
        Ipv6AllowedForDualStack: false
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /gateway_test/getGoodsDetail
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /gateway_test/{gateway_test+}
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /{gateway_test+}
            Method: ANY
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto